name: build-image-push-to-ghcr

on:
  schedule:
  - cron: "13 */6 * * *"
  push:
  workflow_dispatch:

env:
  IMAGE_NAME: sslscan-ci

jobs:
  run:
    runs-on: ubuntu-latest
    steps:       
      - 
        name: timestamp
        shell: bash
        run: echo "TS=$(date +%s)" >> $GITHUB_ENV
      - 
        name: Checkout repository
        uses: actions/checkout@v3
      - 
        name: Build image
        run: docker build . -t $IMAGE_NAME
      -
        name: Run to test
        run: docker run --rm $IMAGE_NAME
      -
        name: Login to ghcr
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      -
        name: Push image to ghcr
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME
          docker tag $IMAGE_NAME $IMAGE_ID:$TS
          docker push $IMAGE_ID:$TS
