name: build-image-push-to-ghcr

on:
  #schedule:
  #- cron: "13,43 * * * *"
  
  workflow_dispatch:
  
jobs:
  build-job:
    runs-on: ubuntu-latest
    steps:       
 #     - name: Checkout repository
 #       uses: actions/checkout@v3
      - name: timestamp
        shell: bash
        run: echo "TS=$(date +%s)" >> $GITHUB_ENV
      - name: print ts
        run: echo $TS

#       - name: Build and push latest image
#         uses: ./
#         with:
#           github-push-secret: ${{secrets.GITHUB_TOKEN}}
#           docker-image-name: sslscan-ci
#           docker-image-tag: $TS
#           dockerfile-path: ./Dockerfile
#           build-context: ./
    
#echo "{environment_variable_name}={value}" >> $GITHUB_ENV
