name: build-image-push-to-ghcr

on:
  #schedule:
  #- cron: "13,43 * * * *"
  push:
  workflow_dispatch:

env:
  IMAGE_NAME: sslscan-ci

jobs:
  run:
    runs-on: ubuntu-latest
    steps:       
      - 
        name: timestamp
        shell: bash
        run: echo "TS=$(date +%s)" >> $GITHUB_ENV
      - 
        name: Checkout repository
        uses: actions/checkout@v3
      - 
        name: Build image
        run: docker build . -t $IMAGE_NAME --label $TS
      -
        name: Run to test
        run: docker run --rm $IMAGE_NAME:$TS
